import { errorMessage as describeError } from '@/shared/api/errors'
export const validationFieldLabels: Record<string, string> = {
  id: '编号',
  name: '名称',
  channel: '渠道',
  workflow_id: '工作流',
  sources: '数据来源',
  channels: '通知渠道',
  options: '选项',
  timeout: '超时时间',
  retries: '重试次数',
  analyses: '分析任务',
  ai: '供应商渠道',
  model: '模型',
  prompt: '提示词',
  fan_in: '汇总设置',
  order: '汇总顺序',
  source_overrides: '数据来源的本次设置',
  channel_overrides: '通知渠道的本次设置',
  recipient: '收件人',
  sender: '发件人',
  host: '服务器地址',
  port: '端口',
  username: '账号',
  password: '凭据',
  api_key: 'API 密钥',
  base_url: '服务地址',
  after: '起始时间',
  before: '截止时间',
  limit: '每页数量',
  offset: '分页位置',
}

export const errorMessage = (cause: unknown) => describeError(cause, validationFieldLabels)
