import {
  Database,
  Bot,
  Mail,
  Workflow,
  Play,
  Menu,
  Cpu,
  Settings,
  Sun,
  Moon,
  LayoutDashboard,
  Plus,
  Square,
  Send,
  GitFork,
  Sparkles,
  FileText,
  Pause,
  RotateCcw,
  Sliders,
  Layers,
  Search,
  Copy,
  Check,
  CornerDownLeft,
  Terminal,
  Zap,
  ChevronRight,
  ChevronDown,
  History,
  Archive,
  Shield,
  Activity,
  Info,
  Pencil,
} from 'lucide-vue-next'

export const icons = {
  database: Database,
  bot: Bot,
  mail: Mail,
  workflow: Workflow,
  play: Play,
  menu: Menu,
  cpu: Cpu,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  dashboard: LayoutDashboard,
  plus: Plus,
  square: Square,
  send: Send,
  fork: GitFork,
  sparkles: Sparkles,
  file: FileText,
  pause: Pause,
  rotate: RotateCcw,
  sliders: Sliders,
  layers: Layers,
  search: Search,
  copy: Copy,
  check: Check,
  enter: CornerDownLeft,
  terminal: Terminal,
  zap: Zap,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  history: History,
  archive: Archive,
  shield: Shield,
  activity: Activity,
  info: Info,
  edit: Pencil,
} as const
export type IconName = keyof typeof icons
